
spring.application.name=order-api

server.port=${SERVER_PORT:8081}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:172.16.15.48:9094}

app.kafka.orders-topic=orders.created.v1
spring.kafka.admin.fail-fast=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.max.block.ms=5000
spring.kafka.producer.properties.request.timeout.ms=10000
spring.kafka.producer.properties.delivery.timeout.ms=15000

